# authors = ["Control Owl <eq[at]r-o0-t[dot]wtf>"]
# license = "CC-BY-NC-ND-4.0  [2023-2026]  Control Owl"

# -.-. --- .--. -.-- .-. .. --. .... - / -.-. --- -. - .-. --- .-.. / --- .-- .-..

[package]
name = "eQ"
description = "High-Performance Cryptographic Key Generator"
version = "1.6.0"
authors = ["Control Owl <eq[at]r-o0-t[dot]wtf>"]
license = "CC-BY-NC-ND-4.0"
repository = "https://github.com/control-owl/eQ"
readme = "README.md"
edition = "2024"
build = "build.rs"

# -.-. --- .--. -.-- .-. .. --. .... - / -.-. --- -. - .-. --- .-.. / --- .-- .-..

[dependencies]

# GUI
egui = "0.36.1"
eframe = "0.36.1"
egui_extras = { version = "0.36.1", features = ["svg", "image", "all_loaders"] }
egui_commonmark = { version = "0.25.0", features = ["load-images"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
rfd = "0.17.2"
svg = "0.18.0"

# System and environment
sysinfo = "0.39.6"
getrandom = "0.4.3"
include_dir = "0.7.4"

# Crypto primitives and hashing
sha2 = "0.11.0"
sha3 = "0.12.0"
tiny-keccak = { version = "2.0.2", features = ["sha3", "keccak"] }
ripemd = "0.2.0"
ring = "0.17.14"

# Curve libraries
secp256k1 = "0.31.1"
ed25519-dalek = "3.0.0"
ed25519-bip32 = "0.4.3"
curve25519-dalek = "5.0.0"
sp-core = "43.0.0"
num-bigint = "0.5.1"

# Encodings and formatting
hex = "0.4.3"
bs58 = "0.5.1"
bech32 = "0.12.0"
base32 = "0.5.1"
base64 = "0.23.1"
base58-monero = "2.1.0"
crc32fast = "1.5.0"
blake2 = "0.10.6"
blake2b_simd = "1.0.4"
digest = "0.11.3"
ciborium = "0.2.2"

# Secrets
shamir_share = "0.2.1"
zeroize = { version = "1.9.0", features = ["derive"] }

# ANU
ureq = "3.3.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

# eQ-OS
egui_keyboard = { version = "0.7.0", optional = true }


# -.-. --- .--. -.-- .-. .. --. .... - / -.-. --- -. - .-. --- .-.. / --- .-- .-..

[features]
default = []
dev = []
osk = ["egui_keyboard"]
eq-os = ["egui_keyboard"]

# -.-. --- .--. -.-- .-. .. --. .... - / -.-. --- -. - .-. --- .-.. / --- .-- .-..

[[bin]]
name = "eQ"
path = "src/main.rs"

[lib]
name = "e_q"
path = "src/lib.rs"

# -.-. --- .--. -.-- .-. .. --. .... - / -.-. --- -. - .-. --- .-.. / --- .-- .-..

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "eQ.EXE"
LegalCopyright = "CC-BY-NC-ND-4.0 (2023-2026) Control Owl"
FileDescription = "Crypto key generator"

[package.metadata.excluded]
exclude = ["build.rs"]

# -.-. --- .--. -.-- .-. .. --. .... - / -.-. --- -. - .-. --- .-.. / --- .-- .-..
